name: CI

on: [push]

jobs:
  php:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: [7.4, 8.3]
    steps:
    - uses: actions/checkout@v1
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
    - name: Install dependencies
      run: composer install --no-interaction --no-progress
    - name: Run tests
      run: vendor/bin/phpunit --verbose --fail-on-warning --coverage-text
    - name: Run phpstan
      run: vendor/bin/phpstan analyse
